### ISSUE TITLE
Build on Ubuntu 20.04 / ROS Noetic fails

### ISSUE THREAD

**Issue by Ly0n** [ceptontech/cepton_sdk_redist#15]
Hi Cepton,

the build of current version v1.17.7 fails on my Ubuntu 20.04.
When jumping back to v1.17.6 it still fails but I was able to get it running changing the `ros/CMakeLists.txt`:
```
set(CMAKE_CXX_STANDARD 11)
```
to 
```
set(CMAKE_CXX_STANDARD 14)
```
This is caused by the PCL library that is using C++14 in ROS Noetic.

**Comment by BestVanRome** [comment]
I have the same issue with current version v1.18.3. Aswell Ubuntu 20.04.

The PCL error disappears, if I do the above but then the next error arises:
```In file included from /opt/catkin_cepton_ws/src/cepton_sdk_redist/ros/third_party/cepton_sdk/include/cepton_sdk_util.hpp:812,  
                 from /opt/catkin_cepton_ws/src/cepton_sdk_redist/ros/third_party/cepton_sdk/include/cepton_sdk_api.hpp:13,  
                 from /opt/catkin_cepton_ws/src/cepton_sdk_redist/ros/src/subscriber_nodelet.hpp:9,  
                 from /opt/catkin_cepton_ws/src/cepton_sdk_redist/ros/src/subscriber_nodelet.cpp:1:  
/opt/catkin_cepton_ws/src/cepton_sdk_redist/ros/third_party/cepton_sdk/include/cepton_sdk_impl/cepton_sdk_util.inc:   
In constructor ‘cepton_sdk::util::Organizer::Organizer(cepton_sdk::SensorInformation)’:   
/opt/catkin_cepton_ws/src/cepton_sdk_redist/ros/third_party/cepton_sdk/include/cepton_sdk_impl/cepton_sdk_util.inc:114:10: error:   
‘VISTA_X15’ was not declared in this scope; did you mean ‘VISTA_X120’?
```

**Comment by B7O7B** [comment]
@BestVanRome This should help fix your issue https://github.com/ceptontech/cepton_sdk_redist/pull/31/commits/5fdadca6a6c7579824a996a2d9cef236a5ecb50
Simply comment out the lines below.
"
`    case VISTA_X15:
             m_settings.horizontal_range_radians = to_radians(15.f);
             m_settings.vertical_range_radians = to_radians(18.f);
             break;`
".
